name = "mrixdu-security-bot1"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_id = "5a545b7e-380a-4e5b-9029-7dc42835e9b9"

id = "392025d3162946a19978c46244d09e6c"

[[kv_namespaces]]
binding = "BOT_KV"
id = "392025d3162946a19978c46244d09e6c"

[triggers]
crons = ["*/5 * * * *"]

# Secrets (set with `wrangler secret put`, do not put them here):
#   BOT_TOKEN        -> your Telegram bot token from @BotFather
#   WEBHOOK_SECRET    -> any random string you choose
